title: Awesome Page
author: dreinfried
email: dreinfried@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio for Derek Reinfried

# social links
twitter_username: 
github_username:  dreinfried

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
